#iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Controllers for singular joint ------------------------------------
  # 
  # Effort Position Controllers ---------------------------------------

  # VALUES ARE NOT CORRECT !
  EffortJointInterface_J1_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_1
    pid: {p: 80.0, i: 10.0, d: 8.0, i_clamp_min: -1000, i_clamp_max: 1000}

  EffortJointInterface_J2_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_2
    pid: {p: 80.0, i: 1000.0, d: 10.0, i_clamp_min: -1000, i_clamp_max: 1000}

  EffortJointInterface_J3_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_3
    pid: {p: 80.0, i: 1.0, d: 0.5, i_clamp_min: -1000, i_clamp_max: 1000}

  EffortJointInterface_J4_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_4
    pid: {p: 80.0, i: 10, d: 8.0, i_clamp_min: -1000, i_clamp_max: 1000}

  EffortJointInterface_J5_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_5
    pid: {p: 30.0, i: 0.5, d: 1.0, i_clamp_min: -1000, i_clamp_max: 1000}

  EffortJointInterface_J6_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_6
    pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_min: -1000, i_clamp_max: 1000}

  EffortJointInterface_J7_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_7
    pid: {p: 1.0, i: 0.01, d: 0.1, i_clamp_min: -1000, i_clamp_max: 1000}

  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_J1_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_1

  PositionJointInterface_J2_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_2
    
  PositionJointInterface_J3_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_3
    
  PositionJointInterface_J4_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_4
    
  PositionJointInterface_J5_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_5
    
  PositionJointInterface_J6_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_6
    
  PositionJointInterface_J7_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_7
    
  # Forward Velocity Controllers ---------------------------------------
  VelocityJointInterface_J1_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_1
    
  VelocityJointInterface_J2_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_2
    
  VelocityJointInterface_J3_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_3
    
  VelocityJointInterface_J4_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_4
    
  VelocityJointInterface_J5_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_5
    
  VelocityJointInterface_J6_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_6
    
  VelocityJointInterface_J7_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_7
    
    
  # Trajectory Controllers ---------------------------------------
  #   
  # Effort Position Controllers ---------------------------------------
  EffortJointInterface_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
      
      # VALUES ARE NOT CORRECT !
    gains:
      iiwa_joint_1: {p: 50.0,  d: 10, i: 1.5, i_clamp: 3}
      iiwa_joint_2: {p: 20.0,  d: 8, i: 1.0, i_clamp: 3}
      iiwa_joint_3: {p: 8.5,  d: 2, i: 1.5, i_clamp: 3}
      iiwa_joint_4: {p: 5.1,  d: 1.3, i: 1.2, i_clamp: 3}
      iiwa_joint_5: {p: 2.3,  d: 0.3, i: 0.5, i_clamp: 3}
      iiwa_joint_6: {p: 1.3,  d: 0.3, i: 0.3, i_clamp: 3}
      iiwa_joint_7: {p: 1.7,  d: 0.2, i: 0.25, i_clamp: 1}

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
    
  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
    
  # Forward Velocity Controllers ---------------------------------------
  VelocityJointInterface_trajectory_controller:
    type: velocity_controllers/JointTrajectoryController
    joints: 
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
      
      # VALUES ARE NOT CORRECT !
    gains:
      iiwa_joint_1: {p: 500,  d: 30, i: 15, i_clamp: 30}
      iiwa_joint_2: {p: 200,  d: 10, i: 10, i_clamp: 30}
      iiwa_joint_3: {p: 65,  d: 10, i: 15, i_clamp: 30}
      iiwa_joint_4: {p: 31,  d: 7, i: 12, i_clamp: 30}
      iiwa_joint_5: {p: 23,  d: 3, i: 5, i_clamp: 30}
      iiwa_joint_6: {p: 13,  d: 3, i: 3, i_clamp: 30}
      iiwa_joint_7: {p: 17,  d: 2, i: 2.5, i_clamp: 10}

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default




